sp:
  user-service:
    users:  再试一哈

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
        
# 必须用post请求手动刷新http://localhost:8101/actuator/refresh